// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqsrnnseyykcvvfjqewy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxc3JubnNleXlrY3Z2ZmpxZXd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM1ODA2NTUsImV4cCI6MjA0OTE1NjY1NX0.bbjhbOqMx53JHajUyHmGZxXTA0p50R5OvXa2BFLtc1Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);